### ISSUE TITLE
It may make sense to upstream it to https://github.com/kaitai-io/kaitai_struct_formats

### ISSUE THREAD

**Issue by KOLANICH** [principia-preservation-project/kaitai#1]

**Comment by rollerozxa** [comment]
Do they allow submodules? These kaitai files are mostly incomplete so I feel like upstreaming it would only create an outdated mirror. It's formats for an obscure mobile game anyways, that repository seems to mostly be more general and popular file formats, whereas these file formats would neither be of any use to or comprehensible to anyone outside of myself who have spent a large amount of time reverse engineering the game.

**Comment by KOLANICH** [comment]
>Do they allow submodules? 

I guess, no.

>These kaitai files are mostly incomplete so I feel like upstreaming it would only create an outdated mirror.

The trick is to have a copy of KSF and do development within its file tree, in an own branch. This way the formats and the scripts and the code are already being kinda prepared for upstreaming there. Even if your PR is not yet ready (GH has a feature to mark such PRs as drafts), sending it to that repo allows to get feedback and increase their visibility.

>It's formats for an obscure mobile game anyways, that repository seems to mostly be more general and popular file formats

Maybe, but TBH we already have formats for some games, like FTL, and other niche formats like the ones used in spectroscopy and AFM (I had authored some).

**Comment by KOLANICH** [comment]
And please note, the PRs are there pending for years because maintainers usually don't have enough time to review them fully. But they and other users still do some review, so even if it won't be merged immediately, you will still benefit from the upstreaming.

**Comment by rollerozxa** [comment]
> The trick is to have a copy of KSF and do development within its file tree, in an own branch. This way the formats and the scripts and the code are already being kinda prepared for upstreaming there.

> And please note, the PRs are there pending for years because maintainers usually don't have enough time to review them fully.

Sounds like a complete waste of everyone's time. Send a pull request yourself if you are so extremely keen on it, because I don't want to deal with that.
